### ISSUE TITLE
Double-precision inputs from python become IDL floats (single-precision)

### ISSUE THREAD

**Issue by jessiemcd** [wtbarnes/hissw#31]
Lists of double (or extended) precision values (dtypes np.float64 or np.float128) used as inputs arrive in IDL as floats (type code 4, single precision). See simple example below, python code first followed by content of idl script. 

```python
import numpy as np
import hissw

#Make double precision + extended precision lists of random values, and verify data types
input_list = list(np.random.rand(10))
input_list_extended = list(np.random.rand(10).astype(np.longdouble))
print(type(input_list[0]))
print(type(input_list_extended[0]))

inputs = {'input_list': input_list, 'input_list_extended': input_list_extended}
ssw = hissw.Environment()
ssw_resp = ssw.run('/path/to/script/floattest.pro', args=inputs)
```

```idl
;IDL Script floattest.pro

print, 'List of random numbers which were double precision in Python:'
INPUTLIST = {{ input_list }}
print, INPUTLIST 
print, 'Size of first entry: ', size(INPUTLIST[0])

print, 'List of random numbers which were extended precision in Python:'
INPUTLIST_EXTEND = {{ input_list_extended }}
print, INPUTLIST_EXTEND
print, 'Size of first entry: ',size(INPUTLIST_EXTEND[0])
```

**Comment by wtbarnes** [comment]
Ok I can reproduce this on my machine as well. My output looks something like,

```
List of random numbers which were double precision in Python:
     0.723843     0.461769    0.0621194     0.817986     0.567312     0.709516
     0.340108     0.163114     0.930852     0.696821
Size of first entry:            0           4           1
List of random numbers which were extended precision in Python:
     0.511192     0.652938     0.689855     0.897582     0.341163    0.0749124
     0.900197     0.464777     0.854453     0.574005
Size of first entry:            0           4           1
```

Just to be explicit, the expectation is that the second number in the array returned by `SIZE` should be 5 instead of 4 correct? I'm basing this off of this help page: https://www.l3harrisgeospatial.com/docs/size.html

**Comment by jessiemcd** [comment]
Yes, that is correct!

**Comment by wtbarnes** [comment]
As a first guess, I suspect this is because `hissw` relies on the string representation of a list to represent numerical arrays. It may be that when representing the list as a string, it is truncating each entry such that precision is lost and doubles become single-precision floats.

Another question: when I create a variable that represents a floating point number, how do I guarantee that that variable is a double-precision floating point value?

**Comment by jessiemcd** [comment]
If you're asking about how to do this in IDL, you can use `double()` to change the type of a value to be double precision. You can then take advantage of the face that arithmetic preserves the higher-precision type:
```
IDL> double(1)/3
      0.33333333333333331
IDL> float(1)/3
      0.33333334
IDL> 1/3
       0
```
Additionally, you can specify the data type when creating constants. I always forget the syntax for this, so I usually only use it for larger numbers when I would already be using scientific notation:
```
IDL> 1.D
       1.0000000000000000
IDL> 1.E
       1.0000000
IDL> 1E+10
   1.0000000e+10
IDL> 1D+10
       10000000000.000000
```
There is more information in the following link under the heading "Floating-Point and Double-Precision Constants": https://www.l3harrisgeospatial.com/docs/defining_and_using_const.html#constants_818058343_701726

Additionally, there is a /double flag available when making an array which will make all values double precision floats, and a built-in function `dindgen` similar to `np.arrange` that specifically makes an increasing array of doubles.
https://www.l3harrisgeospatial.com/docs/make_array.html#TYPE 
https://www.l3harrisgeospatial.com/docs/dindgen.html

**Comment by wtbarnes** [comment]
@jessiemcd I think should now be resolved by #32 with the addition of the `force_double_precision_filter`. If you pull down the latest version from GitHub and modify your IDL script above to be,

```idl
;IDL Script floattest.pro

print, 'List of random numbers which were double precision in Python:'
INPUTLIST = {{ input_list | force_double_precision }}
print, INPUTLIST 
print, 'Size of first entry: ', size(INPUTLIST[0])

print, 'List of random numbers which were extended precision in Python:'
INPUTLIST_EXTEND = {{ input_list_extended | force_double_precision }}
print, INPUTLIST_EXTEND
print, 'Size of first entry: ',size(INPUTLIST_EXTEND[0])
```

The output should now be something like

```idl
List of random numbers which were double precision in Python:
      0.38701972      0.39714535      0.41908539      0.49686550      0.79868530
      0.84018735      0.45899108      0.94885019      0.67142288      0.28960234
Size of first entry:            0           5           1
List of random numbers which were extended precision in Python:
      0.65914494      0.83123126      0.98263299      0.91399852      0.54612130
      0.54969574      0.68435703      0.97690220      0.23865732      0.42071446
Size of first entry:            0           5           1
```

where the size now indicates that the arrays in IDL have double floating point precision.

**Comment by jessiemcd** [comment]
Works great, thanks for making this fix!

**Comment by wtbarnes** [comment]
Great! This should be in the released version now as well.
