### ISSUE TITLE
typos in aia example

### ISSUE THREAD

**Issue by grahamkerr** [wtbarnes/hissw#9]
Very minor, but there are some typos in the aia_get_response example - the logt variables (and interp_logt) should be logte (interp_logte)... or the variables passed into interpol() should have the 'e' removed. 

Great package btw, I was very pleased to learn it existed!

**Comment by wtbarnes** [comment]
Ah don't know how I missed that. Thanks! Unfortunately, the example code in the docs isn't actually run when I build the documentation so bugs annoyingly may sneak in. I should probably figure out a better solution for this.

**Comment by wtbarnes** [comment]
Actually fixed in #12
